// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALuFa5Jp_XtfDGckrfc_zLqO8eXu_DrGU',
    appId: '1:543818472670:web:c7b3864cb6a4bd94e2f64f',
    messagingSenderId: '543818472670',
    projectId: 'quizz-app-ce3e9',
    authDomain: 'quizz-app-ce3e9.firebaseapp.com',
    storageBucket: 'quizz-app-ce3e9.appspot.com',
    measurementId: 'G-KZQSN8NC54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCba-uaQDfDuUngr4VGViRKGTZd6muRasc',
    appId: '1:543818472670:android:bd53d3e490b715b9e2f64f',
    messagingSenderId: '543818472670',
    projectId: 'quizz-app-ce3e9',
    storageBucket: 'quizz-app-ce3e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSCEBsbOt5taAldfxqVdaW4QcwaCcGHkY',
    appId: '1:543818472670:ios:baced68404812729e2f64f',
    messagingSenderId: '543818472670',
    projectId: 'quizz-app-ce3e9',
    storageBucket: 'quizz-app-ce3e9.appspot.com',
    iosClientId: '543818472670-p4mj2ddb81ptfk28vvkoheka6597v3j4.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizzApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSCEBsbOt5taAldfxqVdaW4QcwaCcGHkY',
    appId: '1:543818472670:ios:baced68404812729e2f64f',
    messagingSenderId: '543818472670',
    projectId: 'quizz-app-ce3e9',
    storageBucket: 'quizz-app-ce3e9.appspot.com',
    iosClientId: '543818472670-p4mj2ddb81ptfk28vvkoheka6597v3j4.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizzApp',
  );
}
